Introducing a basic ('toy') model
========================================================

This is the basic RBC model with endogenous labor and logarithmic preferences, with two small additions regardig the productivity process. The name basic comes from de fact that many common modifications are absent: variable capital utilizacion, non-TFP (or non-labor) shocks, adjustment costs, imperfect information, multiple economic sectors, borrow constraints and imperfect information to name a few. The only non-basic feature is that the economy is non-stationary and there are permanent and transitory shocks not to the level of productivity but to its growth rate. We have started with this bare bones model because we want to investigate the effect on labor response  of adding imperfect information about the trend of productivity and of model uncertainty at a basic level. Later on we could put back some of the additional features. The presence of a second type of productivity, investment specific shocks, it's already planned as it is changing the assumption of logarithmic preferences.

## Things to look for##

- specification of productivity growth
- balanced growth path and transformed variables
- income and substitution effects of changes in productivity
- first order labor solution 

